language: node_js

node_js:
  - '7'
  
services:
  - postgresql
  - redis-server

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  postgresql: "9.6"

before_install:
  - npm install -g grunt-cli
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -U postgres -d "travis_ci_test" -a -f ./db/init.sql

script:
  - "npm run cover"
    
env:
  - CXX=g++-4.8